### PR TITLE
minor improvements to learning tests

### PR DESCRIPTION
**Pull request by ilastikdev**
... and conservation tracking test

### CODE REVIEW

**Comment by chaubold** [comment]
@ilastikdev please list all the important changes when creating a PR (or even better, create separate PRs for different issues). Only when looking at the changes I noticed that this PR also fixes the problem of the progress bar not showing up in *Tracking with Learning*.

**Comment by ilastikdev** [comment]
progress bar Qt import error you are reffering to was already fixed in PR #1509

**Comment by chaubold** [comment]
But what is https://github.com/ilastik/ilastik/pull/1521/commits/87fd86a2babe2d3a0b2576c2f9b4420628d74340 doing then? That's exactly why I asked you do document all changes.

**Comment by ilastikdev** [comment]
it makes sure that these calls execute in gui threads
see https://github.com/ilastik/ilastik/blob/master/ilastik/utility/gui/threadRouter.py

**Pull request merged**
