### PR TITLE
fix multicut workflow for py3

### PR DESCRIPTION
**Pull request by akreshuk**
With this and ilastik/ilastikrag@addf55bab031af910aadddeb28c94206cfaa1932 multicut workflow works in master

### CODE REVIEW

**Comment by akreshuk** [comment]
For the sake of not setting a bad example, I won't merge it myself.

**Comment by stuarteberg** [comment]
Who should merge it then?

**Comment by stuarteberg** [comment]
LGTM, but I can't evaluate the nifty API stuff.  Maybe Constantin can comment?

**Comment by stuarteberg** [comment]
LGTM, but I can't evaluate the nifty API stuff. Maybe @constantinpape can comment?

**Comment by constantinpape** [comment]
@stuarteberg Anna and me did the nifty changes together, so this is fine with me.

**Comment by stuarteberg** [comment]
Ah, makes sense.  I think I even saw a snapshot of your collaboration in action:

untitled

**Comment by akreshuk** [comment]
Thanks for bringing up this picture! I guess I should finally get on Twitter.

**Pull request merged**
