### PR TITLE
let pytest use pytest.ini to discover tests

### PR DESCRIPTION
**Pull request by k-dominik**
in the conda recipe we had practically overridden the paths for tests by specifying `.` as path. So in the gh actions it worked before as no source folders were present (e.g. collection errors out for me locally when the `bin` folder is checked for tests...)

Also add source folders for doctests.

### CODE REVIEW

**Review by btbest — APPROVED** [review]
Looks fine on my machine, though it seems we have a known problem test where the `skipif WIN and GH_ACTIONS` just needs to be `skipif WIN`...

image

**Comment by k-dominik** [comment]
thanks for looking into this @btbest. Bummer about the test not working on windows at all anymore...

**Comment by k-dominik** [comment]
A bit of a bummer, but I didn't find a (quick) way to fix the tests for windows. Did these not run before, or why does this surface with this PR?

**Comment by btbest** [comment]
I see now that it actually passes when I run it within a full run, but fails when I run it individually. So we don't have to skip it in CI after all.

When I debug into the function during individual execution, the path and selection are fine, and if I click "Ok" manually, the test passes. In contrast, when I debug into the function from a full test run, `dialog.getSelectedPaths()` doesn't even open a dialog anymore at this point. My first assumption would have been that it must be working directory related, since that's the main difference between full run and individual execution that I'm aware of...

**Comment by k-dominik** [comment]
oh wow...

Maybe that ImageFileDialog class should be refactored so that the functionality can be tested without testing QFileDialog functionality, which I think we can assume to work.

**Pull request merged**
