### PR TITLE
Prevent Qt imports using import hooks

### PR DESCRIPTION
**Pull request by emilmelnikov**
Use import hooks instead of a dummy module in order to prevent importing
PyQt5 in the headless mode by mistake.

Supersedes https://github.com/ilastik/ilastik/pull/1974.

### CODE REVIEW

**Comment by k-dominik** [comment]
all headless tests are failing. I assume that something import `matplotlib` which will import `PyQt5` somewhere. Just a hunch.

**Comment by emilmelnikov** [comment]
When I run tests locally on 8cc74e95cd3958da8e0e93d5c020c9dddf105837 (current master), some windows are briefly popping up from time to time.

**Comment by k-dominik** [comment]
did you limit the test execution somehow, which tests where run? was it maybe expected??

**Comment by emilmelnikov** [comment]
> all headless tests are failing. I assume that something import `matplotlib` which will import `PyQt5` somewhere. Just a hunch.

Yeah... `ilastik.utility` package indirectly imports PyQt, I suspect vigra which unconditionally imports pylab for some reason.

**Comment by emilmelnikov** [comment]
> did you limit the test execution somehow, which tests where run? was it maybe expected??

It seems like these are all the new tests driven by pytest-qt and not marked as GUI tests (test_batchProcessingGui and others).

**Comment by k-dominik** [comment]
btw. this will also be triggered by something like:

```python
_qt_available = True
try:
    import PyQt5
except ImportError:
    _qt_available = False
```
which is not absolutely uncommon. And code like this should also be allowed in headless mode imo.

**Comment by emilmelnikov** [comment]
> btw. will this also be triggered by something like?
> 
> ```python
> _qt_available = True
> try:
>     import PyQt5
> except ImportError:
>     _qt_available = False
> ```
> 
> which is not absolutely uncommon. And code like this should also be allowed in headless mode imo.

That's fine because the blacklist raises ImportError, as if the module doesn't exist. The only task here is to install the blacklist as soon as possible.

**Comment by k-dominik** [comment]
the only question that remains is now, if such a thing is possible at all. I saw that the previous dummy module was probably installed after `PyQt5` was imported already (after `import ilastik` anyway).

**Comment by emilmelnikov** [comment]
> the only question that remains is now, if such a thing is possible at all. I saw that the previous dummy module was probably installed after `PyQt5` was imported already (after `import ilastik` anyway).

It should be possible: PyQt is not an essential Python module, so blocking it should be feasible.

**Comment by emilmelnikov** [comment]
Close in favor of https://github.com/ilastik/ilastik/pull/2099.

**Pull request closed without merging**
