### PR TITLE
Fixes Object classification h5 table export

### LINKED ISSUE #1673: Object Classification h5 table export fails
Users have reported problems when exporting the h5 feature table with tracebacks similar to the following:

```
ERROR 2017-12-06 11:38:44,332 log_exception 25685 140356106745600 Export failed
ERROR 2017-12-06 11:38:44,409 log_exception 25685 140355095164672 Traceback (most recent call last):
  File ".../sources/ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 408, in exportSlots
    self.parentApplet.post_process_lane_export(lane_index)
  File ".../sources/ilastik-meta/ilastik/ilastik/workflows/objectClassification/objectClassificationWorkflow.py", line 360, in post_process_lane_export
    req.wait()
  File ".../miniconda3/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File ".../miniconda3/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 523, in _wait
    self._wait_within_foreign_thread( timeout )
  File ".../miniconda3/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 579, in _wait_within_foreign_thread
    raise_with_traceback(exc_value, exc_tb)
  File ".../miniconda3/envs/ilastik-devel/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File ".../miniconda3/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File ".../sources/ilastik-meta/ilastik/ilastik/applets/objectClassification/opObjectClassification.py", line 820, in do_export
    export_file.add_rois(Default.LabelRoiPath, label_image, "table", settings["margin"], "labeling")
  File ".../sources/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 325, in add_rois
    for i, (slicing, oid) in enumerate(slicings):
  File ".../sources/ilastik-meta/ilastik/ilastik/utility/exportFile.py", line 244, in create_slicing
    yield map(slicing.__getitem__, indices)[:5 - excludes], oid
TypeError: 'map' object is not subscriptable
```

another python 3 switch related issue...

### PR DESCRIPTION
**Pull request by k-dominik**
Problem was related to the python 3 switch, see #1673

In the two changed files, `map` was used and immediately subscripted, which of course resulted in an error, as map returns an iterator.

I've replaced the `map` with list comprehensions, where it is subscripted afterwards. 

fixes #1673

not related to https://github.com/ilastik/ilastik/issues/1671

### CODE REVIEW

**Comment by chaubold** [comment]
LGTM

**Comment by akreshuk** [comment]
Should we add a test? Looks good to me otherwise.

**Comment by k-dominik** [comment]
> Should we add a test? Looks good to me otherwise.

sure, tests never hurt. But we should maybe plan to allocate some time to refurbish the export a la the export in tracking soon.

**Comment by akreshuk** [comment]
Absolutely! I'll merge this one, and let's do some end-of-the-year export clean-up afterwards.

**Pull request merged**
