### PR TITLE
Add workaround for macOS Big Sur

### PR DESCRIPTION
**Pull request by emilmelnikov**
See https://bugreports.qt.io/browse/QTBUG-87014 for details.

Closes https://github.com/ilastik/ilastik/issues/2344

### CODE REVIEW

**Comment by k-dominik** [comment]
Awesome that you got a workaround that quickly. The link you provide does not mention the env variable you are providing. From the source I can only find:

```
        // Enable high-dpi OpenGL for retina displays. Enabling has the side
        // effect that Cocoa will start calling glViewport(0, 0, width, height),
        // overriding any glViewport calls in application code. This is usually not a
        // problem, except if the appilcation wants to have a "custom" viewport.
        // (like the hellogl example)
        if (tlw->supportsOpenGL()) {
            BOOL enable = qt_mac_resolveOption(YES, tlw, "_q_mac_wantsBestResolutionOpenGLSurface",
                                                          "QT_MAC_WANTS_BEST_RESOLUTION_OPENGL_SURFACE");
            [m_contentView setWantsBestResolutionOpenGLSurface:enable];
        }
        BOOL enable = qt_mac_resolveOption(NO, tlw, "_q_mac_wantsLayer",
                                                     "QT_MAC_WANTS_LAYER");

```
I didn't find any more specifics on the side effects of this option. The mention of GLViewport has me slightly worried. Could you try carving with 3D data and make sure or 3D view works as expected?

**Comment by emilmelnikov** [comment]
> The link you provide does not mention the env variable you are providing.

Sorry, I should have posted a link to one of the comments:

https://bugreports.qt.io/browse/QTBUG-87014?focusedCommentId=531203&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-531203

**Comment by k-dominik** [comment]
> > The link you provide does not mention the env variable you are providing.
> 
> Sorry, I should have posted a link to one of the comments:
> 
> https://bugreports.qt.io/browse/QTBUG-87014?focusedCommentId=531203&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-531203

ah, I see. This sounds more reassuring, stating basically that we were using this mode implicitly already on OSX before, but now it's not automatically enabled...

Did you check carving though :)

**Comment by emilmelnikov** [comment]
Unfortunately, you're right: creating/opening a carving workflow blows up:

```pytb
Traceback (most recent call last):
  File "/Users/em/projects/ilastik/ilastik/shell/gui/ilastikShell.py", line 1548, in _loadProject
    self.addApplet(index, app)
  File "/Users/em/projects/ilastik/ilastik/shell/gui/ilastikShell.py", line 1236, in addApplet
    app.getMultiLaneGui(), AppletGuiInterface
  File "/Users/em/projects/ilastik/ilastik/workflows/carving/carvingApplet.py", line 53, in getMultiLaneGui
    from .carvingGui import CarvingGui  # Prevent imports of QT classes in headless mode
  File "/Users/em/projects/ilastik/ilastik/workflows/carving/carvingGui.py", line 45, in <module>
    from volumina.view3d.meshgenerator import MeshGeneratorDialog, mesh_to_obj, labeling_to_mesh
  File "/Users/em/projects/volumina/volumina/view3d/meshgenerator.py", line 5, in <module>
    from pyqtgraph.opengl import MeshData, GLMeshItem
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/pyqtgraph/opengl/__init__.py", line 1, in <module>
    from .GLViewWidget import GLViewWidget
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 2, in <module>
    from OpenGL.GL import *
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 36, in <module>
    _load()
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 33, in _load
    plugin.install(globals())
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 97, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
    def CGL(self): return self.GL
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/em/opt/miniconda/envs/ilastik/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 41, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', 'dlopen(OpenGL, 10): image not found', 'OpenGL', None)
```

**Comment by k-dominik** [comment]
Maybe that's a general Big Sur problem. With your fix all other workflows work at least. (Did you run the legacy gui tests on your mac?).

**Comment by emilmelnikov** [comment]
I think the issue has been described here: https://github.com/python/cpython/pull/21241

The big macOS 11 PR for CPython (which should include a fix to this problem) has been merged a couple of days ago: https://github.com/python/cpython/pull/22855

Strangely, the newest CPython somehow manages to find a shared lib:

* Python 3.9.0 from a fresh env:
  ```
  >>> from ctypes import util; print(util.find_library("OpenGL"))
  /System/Library/Frameworks/OpenGL.framework/OpenGL
  ```
* Python 3.7.8 from the ilastik env:
  ```
  >>> from ctypes import util; print(util.find_library("OpenGL"))
  None
  ```

**Comment by emilmelnikov** [comment]
> Did you run the legacy gui tests on your mac?

Well, they don't work because they are tripping over that shared library issue. As a cruel coincidence, `testCarvingGui.py` runs first.

**Comment by k-dominik** [comment]
> > Did you run the legacy gui tests on your mac?
> 
> Well, they don't work because they are tripping over that shared library issue. As a cruel coincidence, `testCarvingGui.py` runs first.

`pytest -k "not TestCarvingGui" -v --disable-warnings --run-legacy-gui` would skip this and remove all the clutter .

**Comment by emilmelnikov** [comment]
Sorry, I think I forgot to explicitly mention that none of the tests work because volumina always tries to load OpenGL via pyqtgraph.

**Comment by k-dominik** [comment]
could you try with `VOLUMINA_SHOW_3D_WIDGET=0 pytest...`?

**Comment by emilmelnikov** [comment]
> could you try with `VOLUMINA_SHOW_3D_WIDGET=0 pytest...`?

Yes, it works if you do that and also remove all OpenGL-dependent imports from the code path on macOS 11.

However, maybe we should wait for a backport to CPython 3.9 or 3.8, and migrate to that version? I suppose it will be easier for us, and also safer (who knows what else might break?..)

**Comment by emilmelnikov** [comment]
Follow-up: it seems that this issue is caused by Apple removing physical copies of shared libs from a filesystem.

https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes

> New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

**Comment by k-dominik** [comment]
let's maybe hold-off on merging this until we make the next release - until then the problem might have been solved by dependency upgrades...

**Comment by k-dominik** [comment]
merging this for 1.4.0b9

**Pull request merged**
