### PR TITLE
Abort if features and the classifier are out of sync in OpEdgeTraining

### LINKED ISSUE #1842: Error when changing features in multicut while prediction is in process
Hi,

In Multicut on the training tab, pick a lot of features and then let it compute some prediction. While it is computing, click "Select Features" and change the features. Once you click OK, you may be greeted with a nice long error message (see screenshot).

It also writes lots of errors continuously to the console/log. Here is an excerpt:

```
MessageFilter.py", line 52 in timeout
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/errorMessageFilter.py", line 52 in timeout
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/errorMessageFilter.py", line 52 in timeout
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/errorMessageFilter.py", line 52 in timeout
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/errorMessageFilter.py", line 52 in timeout
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/errorMessageFilter.py", line 52 in timeout
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/errorMessageFilter.py", line 52 in timeout
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/errorMessageFilter.py", line 52 in timeout
  File ERROR 2018-09-18 13:38:37,010 excepthooks 96967 139639159506688 Unhandled exception in thread: 'Worker #7'
"/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/errorMessageFilter.py", line 52 in timeout
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/errorMessageFilter.py", line 52 in timeout
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/errorMessageFilter.py", line 52 in timeout
  File "/g/kreshuk/snajder/ilastikERROR 2018-09-18 13:38:37,036 excepthooks 96967 139639184684800 Unhandled exception in thread: 'Worker #4'
-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/errorMessageFilter.py", line 52 in timeout
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/shell/gui/startShellGui.py", line 70 in startShellGui
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik_main.py", line 152 in main
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-metERROR 2018-09-18 13:38:37,036 excepthooks 96967 139639421032192 Traceback (most recent call last):
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/edgeTraining/edgeTrainingGui.py", line 270, in _impl
    edge_probs = op.EdgeProbabilitiesDict.value
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1105, in value
    temp = self[:].wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 301, in execute
    value = request.wait()[0]
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/edgeTraining/opEdgeTraining.py", line 377, in execute
    edge_probabilities = self.EdgeProbabilities.value
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 1105, in value
    temp = self[:].wait()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 301, in execute
    value = request.wait()[0]
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 500, in wait
    return self._wait(timeout)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 526, in _wait
    self._wait_within_request( current_request )
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 651, in _wait_within_request
    raise_with_traceback(exc_value, exc_tb)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/request/request.py", line 324, in _execute
    self._result = self.fn()
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/slot.py", line 884, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/ilastik/ilastik/applets/edgeTraining/opEdgeTraining.py", line 354, in execute
    probabilities = classifier.predict_probabilities(feature_matrix)[:,1]
  File "/g/kreshuk/snajder/ilastik-1.3.0-Linux/ilastik-meta/lazyflow/lazyflow/classifiers/parallelVigraRfLazyflowClassifier.py", line 320, in predict_probabilities
    "Expected features: {}".format( X.shape[1], len(self._feature_names), self._feature_names )
AssertionError: Feature count (1) doesn't match the training feature count (138).
Expected features: ['Raw Data standard_edge_count' 'Raw Data standard_edge_kurtosis'
 'Raw Data standard_edge_maximum' 'Raw Data standard_edge_mean'
 'Raw Data standard_edge_minimum' 'Raw Data standard_edge_skewness'
 'Raw Data standard_edge_sum' 'Raw Data standard_edge_variance'
 'Raw Data standard_edge_quantiles_0' 'Raw Data standard_edge_quantiles_10'
 'Raw Data standard_edge_quantiles_100'
 'Raw Data standard_edge_quantiles_25'
 'Raw Data standard_edge_quantiles_50'
 'Raw Data standard_edge_quantiles_75'
```

features_error

### PR DESCRIPTION
**Pull request by paulhfu**
This fixes #1842

### CODE REVIEW

**Comment by k-dominik** [comment]
I cannot really reproduce the issue, could you come by at sometimes and demonstrate it, please?

**Comment by k-dominik** [comment]
After seeing it being reproduced, this PR should also address the problem that you actually can change the feaures, while live update is active - you shouldn't.

**Comment by paulhfu** [comment]
I also thought about this, but isn't that the point of live update? That you actually can do such things? In object classification features are also mutable during live update.

**Comment by paulhfu** [comment]
This PR is obsolete. It is certainlnly more stable when "select features" is disabled while updating instead of the solution in here. The disabling however will most likely be added in #1910 (avoidinng merge conflicts).

**Pull request closed without merging**
