### PR TITLE
Feature selection

### PR DESCRIPTION
**Pull request by FabianIsensee**
Added feature selection to the pixel classification workflow of Ilastik. It comes with a GUI where the user can conveniently create several feature sets using different methods (and parameters). The segmentations achieved with the different sets are presented and the user can compare them in a volumina viewer. If he decides to select one of the feature sets the features of this set are then automatically written into the SelectionMatrix of the opFeatureSelection

This branch relies on my feature selection package which is available here: https://bitbucket.org/FabianIsensee/feature_selection_clean

feature_selection_dialog

### CODE REVIEW

**Comment by stuarteberg** [comment]
>This branch relies on my feature selection package which is available here: https://bitbucket.org/FabianIsensee/feature_selection_clean

I checked out that repo, but I'm having trouble building it.  I am getting strange cython errors like the one below.  What version of cython are you using?

```
$ python setup.py build_ext
running build_ext
cythoning cython/mutual_information.pyx to cython/mutual_information.c
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    ext_modules=ext_modules
  File "/miniconda/envs/ilastik-devel/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/miniconda/envs/ilastik-devel/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/miniconda/envs/ilastik-devel/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/bergs/Documents/workspace/h5py/.eggs/Cython-0.22.1-py2.7-macosx-10.5-x86_64.egg/Cython/Distutils/build_ext.py", line 163, in run
    _build_ext.build_ext.run(self)
  File "/miniconda/envs/ilastik-devel/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/Users/bergs/Documents/workspace/h5py/.eggs/Cython-0.22.1-py2.7-macosx-10.5-x86_64.egg/Cython/Distutils/build_ext.py", line 170, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/Users/bergs/Documents/workspace/h5py/.eggs/Cython-0.22.1-py2.7-macosx-10.5-x86_64.egg/Cython/Distutils/build_ext.py", line 319, in cython_sources
    full_module_name=module_name)
  File "/Users/bergs/Documents/workspace/h5py/.eggs/Cython-0.22.1-py2.7-macosx-10.5-x86_64.egg/Cython/Compiler/Main.py", line 637, in compile
    return compile_single(source, options, full_module_name)
  File "/Users/bergs/Documents/workspace/h5py/.eggs/Cython-0.22.1-py2.7-macosx-10.5-x86_64.egg/Cython/Compiler/Main.py", line 590, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/Users/bergs/Documents/workspace/h5py/.eggs/Cython-0.22.1-py2.7-macosx-10.5-x86_64.egg/Cython/Compiler/Main.py", line 407, in run_pipeline
    from . import Pipeline
  File "/Users/bergs/Documents/workspace/h5py/.eggs/Cython-0.22.1-py2.7-macosx-10.5-x86_64.egg/Cython/Compiler/Pipeline.py", line 9, in <module>
    from .Visitor import CythonTransform
  File "Cython/Compiler/Visitor.py", line 13, in init Cython.Compiler.Visitor (/var/folders/w5/bd542jpd7cq7hy75d9nxf5ndhndmmh/T/easy_install-Wx3Arf/Cython-0.22.1/Cython/Compiler/Visitor.c:17364)
  File "/Users/bergs/Documents/workspace/h5py/.eggs/Cython-0.22.1-py2.7-macosx-10.5-x86_64.egg/Cython/Compiler/Nodes.py", line 8, in <module>
    cython.declare(sys=object, os=object, copy=object,
AttributeError: 'module' object has no attribute 'declare'
```

**Comment by FabianIsensee** [comment]
Hi Stuart,

I moved into my new office and tried building/installing the package. It 
works just fine here (python setup.py build followed by (sudo) python 
setup.py install).
The version of the cython compiler on this PC is 0.22.1. As soon as I am 
home I can check the version I originally used.

Regards,

Fabian

**Comment by FabianIsensee** [comment]
Hi Stuart,

at home I seem to have the following cython version:

In [2]: cython.__version__
Out[2]: '0.20.1post0'


Regards,

Fabian

**Comment by stuarteberg** [comment]
Doh, the problem was obvious, I just didn't think about it: Your repo has a directory named `cython`, which is accidentally shadowing the real `cython` module when I try to run `python setup.py build_ext`.  I'm not sure why it works on your machine and fails on mine, but renaming the directory fixes the issue.  

Then, I ran into a separate issue because gcc couldn't find the right numpy headers, but that was easily remedied.

**Comment by stuarteberg** [comment]
When I tried this, I got errors like the following traceback.  Before I attempt to determine the cause, can you tell me what type of data you tested with? (2D,3D,4D? how many channels?)

**Comment by FabianIsensee** [comment]
Hi Stuart,

there was no traceback attached to your E-Mail. Could you send it to me 
please?

I tested with what data I could find on my laptop and the ilastik 
website. That was: 2D grayscale, 2D color (RGB), 3D grayscale, 4D grayscale.

Cheers,

Fabian

**Comment by akreshuk** [comment]
Hi Fabian, hi Stuart,

I built it now (with some tiny changes) and it runs. I really like the segmentation preview, makes the tradeoffs of different feature sets very clear. From the UI point of view, I'd change the "Set Size Penalty" setting. If you only consider whether it's > 0.1, I'd put something like a radio button, with "prefer faster, less accurate features" or some other wording like this. If you actually take the value into account, I'd make a slider from 0 to 1, where people could set their value, with the same caption.

The first error I see is when pressing "Feature names" after "Run Feature Selection":
  File "/home/anna/miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/pixelClassification/FeatureSelectionDialog.py", line 402, in _show_feature_name_dialog
    this_channel_name = channel_names[id]
IndexError: list index out of range

**Comment by akreshuk** [comment]
After more testing, I found some other issues with the code, which I expect won't be the last ones. How should we proceed here? @FabianIsensee , are you still available to fix things? Should I fork Fabian's bitbucket repo to ilastik, so that other people can fix the build issues? and make this PR a branch on ilastik/ilastik, so that other people (like me) could push to it? It's a nice piece of work and I'd really like to have it in, but some things need to be fixed before we can merge it.

Another issue I'm not sure how to handle: the tests in Fabian's repo depend on 2 other C libraries. Essentially, he compares the results of his re-implementation to their original. How will we treat such dependencies? And especially their Windows builds?

**Comment by FabianIsensee** [comment]
Hi Anna,

I am glad that you like my work on the feature selection code in 
Ilastik. I am well aware that it is however far from perfect and 
although I am not part of the HCI anymore I would be very happy to help 
out. If you could point out the issues you found I will find time to 
look into them shortly.

Best wishes,

Fabian

**Comment by akreshuk** [comment]
Hi Fabian,

Thanks for your commitment! The first issue is in the comment above - clicking the "show features' names" button fails. Then I'm also concerned about the following:

1. Data with t can not be processed. I tried mitocheck, which is 2D+t and it fails when it tries to cut out a slice to view in the selection dialogue. The error message is TypeError: Can't broadcast (0, 771, 1, 1) -> (762, 771, 1, 1)
2. There is no check that any labels are present or that the classifier has been initialized. It just fails and never recovers.
3. Per design, in 3D one slice is chosen. That's fine, but in my case the slice was not in xy, as it needs to be. Also, it doesn't show exactly which slice is chosen. And I don't understand how it chooses the slice.
4. UI questions, all easy to fix :)
    1.  the names of feature sets are not clear. I guess they are chosen for different parameter settings, but the settings are not in the names. Why not say "time in sec" instead of "ctime"? 
    2. In the "how to" on the left (great that you have it, btw), you mention having many sets with different parameters. However, there is really only one parameter to set - "c". I'd reformulate it as "for different settings of the c parameter". Also, see my previous comment for the selection of this parameter.
5. Why is there a featureSelectionDlg.py in addition to FeatureSelectionDialog.py? Is it used? Can we get rid of it?
6. Do you assume that all features for the image/slice displayed in the dialogue fit in RAM? What if they don't? 
7. Did you have a chance to discuss the overall design with @stuarteberg ? I have some questions about your caching strategies and the first FIXME in the FeatureSelectionDialog code, but if you ran it all by Stuart already, I'm fine with it.

**Comment by ukoethe** [comment]
> the tests in Fabian's repo depend on 2 other C libraries. Essentially, he compares the results of his re-implementation to their original. How will we treat such dependencies?

I suggest to store the reference results produced by the other packages in numpy files which are simply placed in the test directory.

**Comment by akreshuk** [comment]
ok, I figured out point 6., it only computes the features for the points in the training set and, if you zoom into an image, it will show the segmentation on the zoomed in portion in the feature selection dialogue. I suppose it's safe to assume that it would fit in RAM, but we should still check that it fails gracefully if something goes wrong.

**Comment by akreshuk** [comment]
@FabianIsensee , could you start from implementing @ukoethe 's suggestion and rewrite your tests to use reference numbers rather than running the outside library functions? Once that is in, I can merge the ilastik changes and fix the remaining issues one by one.

**Comment by stuarteberg** [comment]
>the tests in Fabian's repo depend on 2 other C libraries. ... How will we treat such dependencies?

I've created conda recipes for these dependencies, and uploaded Mac/Linux binaries to our channel:

```
conda install -c ilastik mitoolbox feast pyfeast
```

(The first two have no test suite, and the last one fails one of its own tests, but at least in the test for a function that Fabian isn't using.)

>And especially their Windows builds?

Honestly, it's probably not worth the trouble. When we test on Windows, we should probably just conditionally skip the tests that require those libraries.

I've made some changes to Fabian's `feature_selection_clean` library \[1\], added a conda-recipe (to the `feature_selection_clean` repo itself) and uploaded Mac/Linux binaries for it:

```
conda install -c feature_selection_clean
```

\[1\]: [github.com/stuarteberg/feature_selection_clean](http://github.com/stuarteberg/feature_selection_clean)

BTW, Should we come up with a better name for this package?


PS -- The `feature_selection_clean` test suite sitll has one failure, not sure if it's a big deal:

```
$ cd feature_selection/tests && nosetests --stop .
F
======================================================================
FAIL: test_CIFE (test_filter_selection.TestFilterFeatureSelection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bergs/Documents/workspace/feature_selection_clean/feature_selection/tests/test_filter_selection.py", line 86, in test_CIFE
    self.assertEqual(set(our_set), set(feast_set))
AssertionError: Items in the first set but not the second:
3
37
44
20
29
5
Items in the second set but not the first:
4
12
51
52
59
60
-------------------- >> begin captured logging << --------------------
feature_selection.filter_feature_selection: INFO: Initialize filter feature selection:
feature_selection.filter_feature_selection: INFO: using filter method: CIFE
feature_selection.filter_feature_selection: INFO: Best feature found was 33 with J_eval= 0.510493. Feature set was []
feature_selection.filter_feature_selection: INFO: Best feature found was 21 with J_eval= 0.447976. Feature set was [33]
feature_selection.filter_feature_selection: INFO: Best feature found was 43 with J_eval= 0.424327. Feature set was [33, 21]
feature_selection.filter_feature_selection: INFO: Best feature found was 61 with J_eval= 0.477468. Feature set was [33, 21, 43]
feature_selection.filter_feature_selection: INFO: Best feature found was 20 with J_eval= 0.474845. Feature set was [33, 21, 43, 61]
feature_selection.filter_feature_selection: INFO: Best feature found was 5 with J_eval= 0.513494. Feature set was [33, 21, 43, 61, 20]
feature_selection.filter_feature_selection: INFO: Best feature found was 3 with J_eval= 0.597186. Feature set was [33, 21, 43, 61, 20, 5]
feature_selection.filter_feature_selection: INFO: Best feature found was 37 with J_eval= 0.570201. Feature set was [33, 21, 43, 61, 20, 5, 3]
feature_selection.filter_feature_selection: INFO: Best feature found was 44 with J_eval= 0.611245. Feature set was [33, 21, 43, 61, 20, 5, 3, 37]
feature_selection.filter_feature_selection: INFO: Best feature found was 29 with J_eval= 0.673252. Feature set was [33, 21, 43, 61, 20, 5, 3, 37, 44]
feature_selection.filter_feature_selection: INFO: Filter feature selection done. Final set is: [33, 21, 43, 61, 20, 5, 3, 37, 44, 29]
test_filter_selection: DEBUG: CIFE
test_filter_selection: DEBUG: ours	[33 21 43 61 20  5  3 37 44 29]
test_filter_selection: DEBUG: feast	[33 21 43 61 52 51 59 60 12  4]
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 4.363s

FAILED (failures=1)
```

**Comment by akreshuk** [comment]
@stuarteberg , thanks! I think if @FabianIsensee doesn't mind we should move the repo to ilastiktools or somewhere else under our organization. I have no idea if the test failure is important though, @ukoethe , what do you think? All other tests pass. I'll rebase this branch on master and try to fix some stuff too.

**Comment by FabianIsensee** [comment]
Hi,
I don't mind at all if you move/rename the repository. Just let me know 
so that I can also work on it. I am very sorry that I didn't find the 
time yet to work on the issues you reported. This is very high up on my 
list! ;-)
The test should not fail to be honest. I will look into it.
Did you make any changes to the repository?
Regards,
Fabian

**Comment by akreshuk** [comment]
No, we didn't make any changes beyond providing the numpy header for building. If you could look into the test failure, that would be great!

**Comment by stuarteberg** [comment]
The `feature_selection` package includes some cython code, but it turns out it's unnecessary: `sklearn` implements the same function, with equal (or better) performance: http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mutual_info_score.html

```python
In [79]: feature_selection.mutual_information.calculate_mutual_information(a,b, base=2.0)
Out[79]: 0.18821512162685394

In [80]: sklearn.metrics.mutual_info_score(a,b)/np.log(2.0)
Out[80]: 0.18821513005741938

In [81]: %timeit feature_selection.mutual_information.calculate_mutual_information(a,b, base=2.0)
1 loops, best of 3: 272 ms per loop

In [82]: %timeit sklearn.metrics.mutual_info_score(a,b)/np.log(2.0)
10 loops, best of 3: 202 ms per loop
```

**Comment by stuarteberg** [comment]
OK, I removed all of the cython code and replaced it with a call to `sklearn.metrix.mutual_info_score()`, and updated conda packages.  Interestingly, that one failing unit test now passes after these changes.

**Comment by stuarteberg** [comment]
I took the liberty of renaming Fabian's package to `ilastik-feature-selection`.  The new home is here:
https://github.com/ilastik/ilastik-feature-selection

I also added a license file (MIT, per Fabian's `setup.py`), and added conda packages for Mac and Linux:

```bash
$ conda install -c ilastik ilastik-feature-selection
$ python -c 'import ilastik_feature_selection'
```

**Comment by stuarteberg** [comment]
I rebased Fabian's branch of ilastik and fixed the import names.  Any further ilastik development on this should be done here:
https://github.com/ilastik/ilastik/tree/feature-selection-rebased

**Comment by akreshuk** [comment]
the modified version has been merged

**Pull request closed without merging**
