### PR TITLE
Add CITATION.cff to repository

### PR DESCRIPTION
**Pull request by m-novikov**
Github supports citation files as described here:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files

You can see how it looks by switching to the branch `m-novikov-add-citation` in this repo

### CODE REVIEW

**Review by k-dominik — COMMENTED** [review]
I like the idea in general to help people find how to cite ilastik. I'm not sure the cff is meant for linking to articles -generating bibtex from it results in:

```bibtex
@misc{Berg_ilastik_interactive_machine_2019,
        author = {Berg, Stuart and Kutra, Dominik and Kroeger, Thorben and Straehle, Christoph N. and Kausler, Bernhard X. and Haubold, Carsten and Schiegg, Martin and Ales, Janez and Beier, Thorsten and Rudy, Markus and Eren, Kemal and Cervantes, Jaime I. and Xu, Buote and Beuttenmueller, Fynn and Wolny, Adrian and Zhang, Chong and Koethe, Ullrich and Hamprecht, Fred A. and Kreshuk, Anna},
        doi = {10.1038/s41592-019-0582-9},
        month = {9},
        title = {ilastik: interactive machine learning for (bio)image analysis},
        url = {https://ilastik.org},
        year = {2019}
}
```

"misc" (which should be an "article") and url should point at the paper, not the website.

see "How to cite" on our website: https://www.ilastik.org/publications.html

reference bibtex file:

```bibtex
@article{berg2019,
	title = {ilastik: interactive machine learning for (bio)image analysis},
	issn = {1548-7105},
	url = {https://doi.org/10.1038/s41592-019-0582-9},
	doi = {10.1038/s41592-019-0582-9},
	abstract = {We present ilastik, an easy-to-use interactive tool that brings machine-learning-based (bio)image analysis to end users without substantial computational expertise. It contains pre-defined workflows for image segmentation, object classification, counting and tracking. Users adapt the workflows to the problem at hand by interactively providing sparse training annotations for a nonlinear classifier. ilastik can process data in up to five dimensions (3D, time and number of channels). Its computational back end runs operations on-demand wherever possible, allowing for interactive prediction on data larger than RAM. Once the classifiers are trained, ilastik workflows can be applied to new data from the command line without further user interaction. We describe all ilastik workflows in detail, including three case studies and a discussion on the expected performance.},
	journal = {Nature Methods},
	author = {Berg, Stuart and Kutra, Dominik and Kroeger, Thorben and Straehle, Christoph N. and Kausler, Bernhard X. and Haubold, Carsten and Schiegg, Martin and Ales, Janez and Beier, Thorsten and Rudy, Markus and Eren, Kemal and Cervantes, Jaime I. and Xu, Buote and Beuttenmueller, Fynn and Wolny, Adrian and Zhang, Chong and Koethe, Ullrich and Hamprecht, Fred A. and Kreshuk, Anna},
	month = sep,
	year = {2019}
}
```

further reading: https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#credit-redirection

**Comment by m-novikov** [comment]
I think `preferred-citation` should solve this issue https://github.com/citation-file-format/citation-file-format/issues/259

**Comment by m-novikov** [comment]
Then let's pospone it for half a year or so. Preferred citation doesn't seem to be working with github at this point.

**Comment by k-dominik** [comment]
reopened - preferred citation seems to be working as expected now

you can check it out here: https://github.com/ilastik/ilastik/tree/m-novikov-add-citation

generated bibtex entry:

```
@article{Berg_ilastik_interactive_machine,
author = {Berg, Stuart and Kutra, Dominik and Kroeger, Thorben and Straehle, Christoph N. and Kausler, Bernhard X. and Haubold, Carsten and Schiegg, Martin and Ales, Janez and Beier, Thorsten and Rudy, Markus and Eren, Kemal and Cervantes, Jaime I. and Xu, Buote and Beuttenmueller, Fynn and Wolny, Adrian and Zhang, Chong and Koethe, Ullrich and Hamprecht, Fred A. and Kreshuk, Anna},
doi = {10.1038/s41592-019-0582-9},
journal = {Nature Methods},
title = {{ilastik: interactive machine learning for (bio)image analysis}}
}
```

**Pull request merged**
