### PR TITLE
New object features' dialogue

### PR DESCRIPTION
**Pull request by akreshuk**

### CODE REVIEW

**Comment by akreshuk** [comment]
Ready for review/testing, @stuarteberg ! If you can make the actual dialogue look better, that is have the columns really adjusted to contents, just do it, I agree to all changes in the ui file. I couldn't find a way myself.

**Comment by akreshuk** [comment]
Hold on, forgot to change the tests accordingly

**Comment by akreshuk** [comment]
Tracking seems to work for me too, time for review! @stuarteberg , could you take a look?

**Comment by stuarteberg** [comment]
@akreshuk OK, I pushed some changes to the UI:

- Auto-update the help text whenever the mouse hovers over a feature name.
- Removed the '?' column, since it isn't needed any more.
- Changed the layout so that the help text is shown below the feature list.

If that all sounds reasonable, I'll go ahead and merge.

Here's a screenshot:

screen shot 2016-11-30 at 1 00 44 pm

**Comment by akreshuk** [comment]
:thumbsup: :thumbsup: :thumbsup:

**Pull request merged**
