### PR TITLE
Add a docs button to the main viewer window

### PR DESCRIPTION
**Pull request by Amir22010**
hi, this is my new pr with only relevant changes, let me know your view

### CODE REVIEW

**Comment by Amir22010** [comment]
app veyndor failed test

**Comment by k-dominik** [comment]
Hello @Amir22010 , I have reopened your PR. The changes shouldn't cause Appveyor to fail. I retriggered the tests and am sure it will be fine.

**Comment by Amir22010** [comment]
@k-dominik thanks for that, please check again retriggering the appveyor, working on resolving issues regarding object classification

**Comment by k-dominik** [comment]
No Problem. I see that you have commited to master on your branch. This is generally not a good idea. We follow the git flow branching model as described here: https://guides.github.com/introduction/flow/ . So just checkout the feature branch from the current master.

**Comment by Amir22010** [comment]
@k-dominik thanks for this, i will take care of and make a feature branch on my forked project.

**Comment by Amir22010** [comment]
opened new pr with feature branch

**Pull request closed without merging**
