### PR TITLE
[for discussion] Added issue template

### PR DESCRIPTION
**Pull request by k-dominik**
Wanted to add one of these for a long time.
The wording and sequence is not set in stone, let's optimize it together :)

I've submitted an issue using this template and it does take its time: https://github.com/ilastik/ilastik/issues/1821

But the result is quite useful I would say

### CODE REVIEW

**Comment by emilmelnikov** [comment]
Maybe also replace bold lines `**` with headings `##`?

**Comment by k-dominik** [comment]
okay, I have switched from bold font to 2nd level headings `##`. I do agree that it looks nicer: #1821

**Comment by m-novikov** [comment]
LGTM

**Comment by emilmelnikov** [comment]
If the issue author is a developer, maybe we could ask them to provide the exact git revisions?
This could be done with the following shell command, assuming that `basename $(pwd)` is `ilasik-meta`:
```sh
for d in ilastik lazyflow volumina; do
    (cd $d && echo "$d ilastik/$d@$(git rev-parse --verify HEAD)")
done
```

Output:
```
ilastik ilastik/ilastik@3f070fcfb7bac1943815efa9863902e141238600
lazyflow ilastik/lazyflow@f1eaa478381ca27cf1ee43e4a26c96175a914073
volumina ilastik/volumina@fd9c2bf88692320ae00ecaf64795b26174bab7ca
```

Github understands the output format and auto-links the lines to the corresponding project revisions, so the author can copy-paste the output right into the issue body.

**Comment by k-dominik** [comment]
> ilastik ilastik/ilastik@3f070fcfb7bac1943815efa9863902e141238600
   lazyflow ilastik/lazyflow@f1eaa478381ca27cf1ee43e4a26c96175a914073
   volumina ilastik/volumina@fd9c2bf88692320ae00ecaf64795b26174bab7ca

I like this idea

**Comment by k-dominik** [comment]
@Tomaz-Vieira, @FynnBe any remarks? Otherwise I'd merge...

**Pull request merged**
