### PR TITLE
[Ready] fix for #1099 (and possibly others) - 5d-ified object extraction

### PR DESCRIPTION
**Pull request by burgerdev**
fix for #1099. I'm sure this helps with #1075, too.

### CODE REVIEW

**Comment by burgerdev** [comment]
@christophdecker @akreshuk @(other people involved with OC) can you give this branch a try? Object classification with time series could be much better now...

**Comment by christophdecker** [comment]
So from a very first test with TXY data, I can tell that it's much faster now, but RAM usage is still pretty high. I'll run it on a bigger file tomorrow to be able to give some real numbers. Thanks anyway, this makes ilastik much more useful for people with TXY data!

**Comment by burgerdev** [comment]
I found another source for slowness: `OpObjectCenterImage` was splitting up its dirty propagation in time, although it has no reason to - it always gets a range as roi. Fixed this in db091a4.

**Comment by stuarteberg** [comment]
This PR looked fine to me, but I did make one change before I merged it: I parallelized the computation across time slices (with a `RequestPool`).

**Pull request merged**
