### PR TITLE
highlight selected applet drawer item

### PR DESCRIPTION
**Pull request by k-dominik**
addresses #1513
In ilastik, the currently selected (workflow) item in the app drawer doesn't stand out particularly well:

ilastik-drawer-old

now the title of the current drawer is highlighted in bold font as follows:

ilastik-drawer-new

### CODE REVIEW

**Comment by akreshuk** [comment]
Looks much better! Do you think this could be extended to fix #1513?

**Comment by k-dominik** [comment]
ok, this should be ready to be merged, looks like this on my machine:

next-try

**Comment by k-dominik** [comment]
latest update, added a thin line below the active applet heading:

thinline

**Comment by k-dominik** [comment]
@akreshuk @stuarteberg @chaubold : any more thoughts on this?

**Comment by akreshuk** [comment]
Should be merged as far as I'm concerned

**Comment by k-dominik** [comment]
hmmm, or should we wait for this until the master->py3 switch? Making it look different after the switch also has a nice ring to it.

**Comment by chaubold** [comment]
I would rather not introduce new _features_ on master anymore, it was supposed to be only a few bug fixes before we release the last Py 2.7 version.

This doesn't mean I don't like the improved highlighting of the current applet, I'd just postpone it to the Py3 switch.

**Comment by chaubold** [comment]
I just tried this on macOS and am not so convinced about the white backgrounds...

I guess I'd prefer for bold font of the selected applet only, or additionally a different color to highlight the active one, but not changing the color of the other tabs...

Before:
screen shot 2017-08-24 at 13 53 08

After:
screen shot 2017-08-24 at 13 51 57

**Comment by k-dominik** [comment]
superseeded by https://github.com/ilastik/ilastik/pull/1900

**Pull request closed without merging**
