### PR TITLE
Fix counting gui test freeze

### PR DESCRIPTION
**Pull request by k-dominik**
The main commit is "solves" the problem of the gui test halting is https://github.com/ilastik/ilastik/commit/533006600dc185135cd7c6473ecfdb952a79bf09 . Unfortunately it is not a real solution, but rather a mere hack: Due to not yet clearly identified problems in lazyflow, `OpCacheFixer` will block the main thread if `OpCacheFixer.fixAtCurrent` is changed, while at the same time someone pulls from its output.

In any case, this will let the tests run through for now.
Note, that there will still be an error in the tests, which I will address in a different PR (out of scope).

This PR includes a few minor changes that I have introduced to make it more like pixelClassification.

Summary of other changes:

* didn't see a reason why `OpDenseLabelArray` was used, so changed it to `OpCompressedLabelArray`, as in pixel classification
* there was a problem serializing to hdf5 with pickled objects. these should be saved as `numpy.void`
* the callback added in https://github.com/ilastik/ilastik/commit/be2fb4c0528085a951ab7a62908cd2eacc08590d, works around the a part of the problem mentioned in https://github.com/ilastik/ilastik/issues/956, where the gaussian would only be drawn in the current tile and not across tile borders

### CODE REVIEW

**Comment by k-dominik** [comment]
Ok, hang on, I have pushed a fix for the failing test as well, because it's such a tiny one.

I think this test has never really worked (have confirmed this in python2 as well). The only difference, is that, with the cache in place, those values were never evaluated, hence `0.0 == 0.0`. Without the cache, however the actual computation is triggered. The box label is rounded to 1 digit precision. So in the test, one cannot compare that value to the output of the operator.

**Comment by k-dominik** [comment]
Yeah, the discussions with @akreshuk were extremely helpful!

Am 26.09.2017 5:34 nachm. schrieb "Carsten Haubold" <
notifications@github.com>:

**Comment by akreshuk** [comment]
Oh the pleasure of the green check!

**Comment by stuarteberg** [comment]
>Oh the pleasure of the green check!

+1

>didn't see a reason why OpDenseLabelArray was used, so changed it to OpCompressedLabelArray, as in pixel classification

Sorry about that.  The reason it exists is that the `OpCompressedLabelArray` adds a little lag to the UI since labels need to be compressed/decompressed, and it uses HDF5 to do it instead of vigra.  Since Counting only supports 2D data, simply storing a dense array of labels is not RAM-intensive, and it is faster.

BUT... I completely agree with your decision to make the switch.  It's better to just be consistent with the other workflows.  And if there weren't proper comments explaining the purpose of the strange operator, then it deserves to die. :-)

**Comment by k-dominik** [comment]
Thanks @stuarteberg for the insight. And good to know that we can expect a little less performance when annotating. If that gets too annoying, we at least know what to do.

**Comment by k-dominik** [comment]
Okay, I'll merge it in then.

**Pull request merged**
