### PR TITLE
Export tables

### LINKED ISSUE #2144: Tracking plugin export broken if data copied to project file
## Describe the bug
Using a plugin for export will result in an error in Tracking.

## Expected behavior
Export should work.

## To Reproduce
Within the Animal Tracking workflow
1. Add some data (I've used mitocheck) in the data selection applet, copy _raw_data_ dataset to the project file
2. Do thresholding, train the object count classifier
3. In export choose _Plugin_ and leave the default settings
4. Hit export -> :boom:

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2019-10-23 10:46:53,445 log_exception 20511 140492707108608 Traceback (most recent call last):
  File ".../ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 418, in exportSync
    lane_index, checkOverwriteFiles=True
  File ".../ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/base/trackingBaseDataExportApplet.py", line 269, in post_process_lane_export
    return self._export_with_plugin(lane_index, checkOverwriteFiles, op.SelectedPlugin.value)
  File ".../ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/base/trackingBaseDataExportApplet.py", line 235, in _export_with_plugin
    filename = self.getPartiallyFormattedName(lane_index, name_format)
  File ".../ilastik-1.3.3-Linux/ilastik-meta/ilastik/ilastik/applets/tracking/base/trackingBaseDataExportApplet.py", line 278, in getPartiallyFormattedName
    dataset_dir = PathComponents(raw_dataset_info.filePath).externalDirectory
AttributeError: 'ProjectInternalDatasetInfo' object has no attribute 'filePath'
```

## Desktop (please complete the following information):
 - ilastik version: 1.3.3
 - OS: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by m-novikov**
fixes #2144

### CODE REVIEW

**Comment by m-novikov** [comment]
Depends on https://github.com/ilastik/lazyflow/pull/329/files

**Comment by k-dominik** [comment]
`testObjectClassificationGui` calls `op_object_classification.configure_table_export_settings(table_export_settings, export_features)`, which doesn't work anymore

**Comment by k-dominik** [comment]
btw, this also fixes #2144 (not even open when you worked on this - great!)

**Comment by k-dominik** [comment]
:+1:

**Pull request merged**
