### PR TITLE
Interactive selection of features by importance

### PR DESCRIPTION
**Pull request by akreshuk**
Works for me for all the datasets I tried, on linux.

### CODE REVIEW

**Comment by akreshuk** [comment]
Sorted out the weird commit history problem, someone please try it now.

**Comment by akreshuk** [comment]
Worked for @ukoethe on windows as well. @stuarteberg , could you give it a quick try on Mac? Just to be sure.

**Comment by chaubold** [comment]
Works fine for me on OSX for a 2D and 3D dataset.

One minor suggestion: show a warning or completely disable the "Suggest Features" button while no annotations have been made, as it gives the rather nasty error message:

```
ERROR 2016-07-07 19:21:14,799 excepthooks 55607 140735309665024 Traceback (most recent call last):
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/applets/pixelClassification/FeatureSelectionDialog.py", line 788, in _run_selection
    self.opFilterFeatureSelection.setupOutputs()
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/ilastik-meta/ilastik/ilastik/applets/pixelClassification/opPixelClassification.py", line 671, in setupOutputs
    self.feature_selector = ilastik_feature_selection.filter_feature_selection.FilterFeatureSelection(data, labels.astype("int"), self._filter_method)
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/lib/python2.7/site-packages/ilastik_feature_selection-0.123-py2.7.egg/ilastik_feature_selection/filter_feature_selection.py", line 47, in __init__
    self._X = normalize_data_for_MI(np.asarray(X))
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/lib/python2.7/site-packages/ilastik_feature_selection-0.123-py2.7.egg/ilastik_feature_selection/filter_feature_selection.py", line 44, in normalize_data_for_MI
    X[:, i] -= X[:, i].min()
  File "/Users/chaubold/opt/miniconda/envs/ilastikdev/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by akreshuk** [comment]
@FabianIsensee , there we go :)

**Comment by stuarteberg** [comment]
Nice.

**Pull request merged**
