### PR TITLE
Add bioimage.io manifest

### PR DESCRIPTION
**Pull request by constantinpape**
Draft for the bioimage.io manifest.
We could also make a new repo `ilastik/models` that contains the manifest and could also hold some of the models itself.
See https://github.com/deepimagej/models.

Still need to replace some of the things copied from the deepimagej template.

See also #2265

### CODE REVIEW

**Comment by constantinpape** [comment]
I thought about this a bit more and I think it would make more sense to have a `ilastik/models` repo where we can also dump models that don't have another repo.
What do you think @k-dominik @m-novikov @FynnBe?
If you agree I can go ahead and create that repo.

**Comment by k-dominik** [comment]
I agree that if we want to add models and the likes, then it probably makes more sense to separate it. 'models' sounds a tad generic for the repo...

**Comment by constantinpape** [comment]
I don't mind a different repo name.
If 'models' sounds too generic we could also go with
'bioimage-io-models'
or
'deep-ilastik-models'

**Comment by FynnBe** [comment]
I like 'bioimage-io-models', they don't all have to be deep. Someone could theoretically add ilastik's random forest as a bioimage-io model...

**Comment by constantinpape** [comment]
> I like 'bioimage-io-models', they don't all have to be deep. Someone could theoretically add ilastik's random forest as a bioimage-io model...

Makes sense; I will create the 'bioimage-io-models' repo later and add the manifest.

**Pull request closed without merging**
